### ISSUE TITLE
Interpret the fraction

### ISSUE THREAD

**Issue by drkamarul** [tinu-schneider/Flatten_the_Curve#1]
Dear Dr Tinu Schneider,

May I ask how to interpret properly the plot.
In a plot with the default parameters and the number of susceptible populations equal to 1000,  the final fraction for 'Daily New Cases in % of the Population' for without intervention equals 85% and for intervention equals 68%, could I interpret the plot like below:

- **850 out of 1000 population will be infected should there is no intervention and 680 will be infected should there is intervention**

**Comment by tinu-schneider** [comment]
Please refer to the original blog post from Michael Höhle [https://staff.math.su.se/hoehle/blog/2020/03/16/flatteningthecurve.html](https://staff.math.su.se/hoehle/blog/2020/03/16/flatteningthecurve.html). There you will find all the background information about the mathematical model.

And please don't use this simple model to make forcasts. The model should give you an impression about the outcome, but it is not intended to calculate anything in detail.
