### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by nealmcb** [tinu-schneider/Flatten_the_Curve#2]
Very glad to see this showing the value of avoiding overshoot - very informative - thank you!

My S/S++/R skills are out-of-date.  Is there a Python version, or analogous code in some other repository in Python?

**Comment by tinu-schneider** [comment]
Sorry Neal, I totally missed your question! And I guess I can't help you with a Python version, nor do I know of anybody who would/could translate it. I hope you find some other sources!
